version: '3.8'
services:
  # 1. Database
  postgres_db:
    image: postgres:15
    container_name: admission_db
    environment:
      POSTGRES_DB: admission_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Java Backend
  admission-service:
    build: .
    ports:
      - "8080:8080" # Сайт (з логіном)
      - "8081:8081" # Метрики (без логіна)
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/admission_system
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=securepassword
    depends_on:
      - postgres_db

  # 3. React Frontend
  frontend:
    build: ./frontend
    container_name: admission_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - admission-service

  # 4. Monitoring (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"


  # 5. Monitoring (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Grafana буде доступна на порту 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: # <--- Оголошуємо том
  prometheus_data:
  postgres_data: