version: '3.8'
services:
  # 1. Database
  postgres_db:
    image: postgres:15
    container_name: admission_db
    environment:
      POSTGRES_DB: admission_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"

  # 2. Java Backend
  admission-service:
    build: .
    container_name: admission_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/admission_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: securepassword

  # 3. React Frontend (NEW!)
  frontend:
    build: ./frontend
    container_name: admission_frontend
    ports:
      - "3000:3000"
    stdin_open: true  # Required for React to work in Docker
    depends_on:
      - admission-service

  # 4. Monitoring (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # 5. Monitoring (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # We use port 3001 because React uses 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus